---
- name: Update Timezone to Europe/Berlin
  copy: content="Europe/Berlin\n" dest=/etc/timezone owner=root group=root mode=0644
  become: true
  register: timezone

- name: Reconfigure Timezone Data
  command: dpkg-reconfigure -f noninteractive tzdata
  become: true
  when: timezone.changed

- name: select keyboard layout
  become: true
  lineinfile:
    dest=/etc/default/keyboard
    regexp="^XKBLAYOUT"
    line="XKBLAYOUT=\"{{ keyboardlanguage }}\""

- name: install screen
  become: true
  apt:
    name=screen
    state=installed
    update_cache=yes
    cache_valid_time=3600

- name: install mosh for ssh
  become: true
  apt:
    name=mosh
    state=installed
    update_cache=yes
    cache_valid_time=3600

- name: install rsync
  become: true
  apt:
    name=rsync
    state=installed
    update_cache=yes
    cache_valid_time=3600

- name: "install rdiff backup"
  become: true
  apt:
    name="rdiff-backup"
    state=installed
    update_cache=yes
    cache_valid_time=3600

- name: install lsof
  become: true
  apt:
    name=lsof
    state=installed
    update_cache=yes
    cache_valid_time=3600

- name: generate German locales
  become: true
  locale_gen:
    name="de_DE.UTF-8"
    state=present

- name: enable tmpfs settings
  become: true
  replace:
    dest=/etc/default/tmpfs
    regexp="^\#{{ item }}"
    replace="{{ item }}=yes"
  with_items:
    - RAMLOCK
    - RAMSHM
    - RAMTMP

- name: set tmpfs size preferences
  become: true
  replace:
    dest=/etc/default/tmpfs
    regexp="^\#{{ item.name }}"
    replace="{{ item.name }}={{ item.value }}"
  with_items: "{{ tmpfssizes }}"

- name: set tmpfs mount points in fstab
  become: true
  mount:
    name="{{ item.mountpoint }}"
    src="tmpfs"
    opts="{{ item.opts }},defaults,mode=0755"
    state=present
    fstype="tmpfs"
  with_items: "{{ tmpfsfstab }}"

- name: enable acl for root directory
  become: true
  mount:
    name="/"
    src="/dev/mmcblk0p2"
    opts="defaults,noatime,acl"
    state=present
    fstype=ext4

- name: install script to create log directories on boot
  become: true
  copy:
    src="logdirectories.sh"
    dest="/etc/init.d/prepare-dirs"
    owner=root
    group=root
    mode=0755

- name: enable script to create log directories on boot
  become: true
  command: update-rc.d prepare-dirs defaults 01 99
    creates=/etc/rc2.d/S01prepare-dirs

- name: install unattended upgrades package
  become: true
  apt:
    name=unattended-upgrades
    state=present
    update_cache=yes
    cache_valid_time=3600

- name: enable updates for jessie
  become: true
  replace:
    dest=/etc/apt/apt.conf.d/50unattended-upgrades
    regexp="//      \"o=Raspbian,n=jessie\";"
    replace="       \"o=Raspbian,n=jessie\";"

- name: enable periodic updates
  become: true
  copy:
    src=10periodic
    dest=/etc/apt/apt.conf.d/10periodic
    owner=root
    group=root
    mode=0644

- name: delete preinstalled pi user
  become: true
  user:
    name=pi
    state=absent
